version: '3.8'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"